# Generated by Django 5.1.4 on 2024-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='created_at',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='target_range',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='result',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
